---
kind: pipeline
name: deploy to washweb.org
steps:
  - name: build quarto site
    image: cynkra/quarto-r:1.4.169-4.3.1
    commands:
      - 'echo "install.packages(\"rmarkdown\")" | r -'
      - quarto render
  - name: deploy to running app instance
    image: git.coopcloud.tech/coop-cloud/docker-cp-deploy:latest
    settings:
      host: washnote.org
      port: 222
      service: washweb_org_app
      source: .
      dest: /usr/share/nginx/html/
      chdir: _site
      deploy_key:
        from_secret: drone_ssh_washnote_org
    when:
      branch:
       - main
---
kind: pipeline
name: deploy to dev.washweb.org
steps:
  - name: build quarto site
    image: cynkra/quarto-r:1.4.169-4.3.1
    commands:
      - 'echo "install.packages(\"rmarkdown\")" | r -'
      - quarto render
  - name: deploy to running app instance
    image: git.coopcloud.tech/coop-cloud/docker-cp-deploy:latest
    settings:
      host: washnote.org
      port: 222
      service: dev_washweb_org_app
      source: .
      dest: /usr/share/nginx/html/
      chdir: _site
      deploy_key:
        from_secret: drone_ssh_washnote_org
    when:
      branch:
       - dev
