---
kind: pipeline
name: deploy to washweb.org
steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /usr/local/lib/R/site-library
    volumes:
      - /tmp/cache:/cache
  - name: build quarto site
    image: cynkra/quarto-r:1.4.169-4.3.1
    commands:
      - 'echo "install.packages(\"rmarkdown\")" | r -'
      - quarto render
  - name: deploy to washweb.org
    image: git.coopcloud.tech/coop-cloud/docker-cp-deploy:latest
    settings:
      host: washnote.org
      port: 222
      service: washweb_org_app
      source: .
      dest: /usr/share/nginx/html/
      chdir: _site
      deploy_key:
        from_secret: drone_ssh_washnote_org
    when:
      branch:
       - main
  - name: deploy to dev.washweb.org
    image: git.coopcloud.tech/coop-cloud/docker-cp-deploy:latest
    settings:
      host: washnote.org
      port: 222
      service: dev_washweb_org_app
      source: .
      dest: /usr/share/nginx/html/
      chdir: _site
      deploy_key:
        from_secret: drone_ssh_washnote_org
    when:
      branch:
       - dev
  - name: rebuild-cache
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - /usr/local/lib/R/site-library
    volumes:
      - /tmp/cache:/cache
