---
kind: pipeline
name: deploy to washweb.org
steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - /usr/local/lib/R/site-library
    volumes:
      - name: cache
        path: /cache
      - name: lib
        path: /usr/local/lib/R/site-library
  - name: build quarto site
    image: cynkra/quarto-r:1.4.169-4.3.1
    commands:
      - 'echo "install.packages(\"rmarkdown\")" | r -'
      - 'echo "install.packages(\"readr\")" | r -'
      - quarto render
    volumes:
      - name: lib
        path: /usr/local/lib/R/site-library
  - name: deploy to washweb.org
    image: git.coopcloud.tech/coop-cloud/docker-cp-deploy:latest
    settings:
      host: washnote.org
      port: 222
      service: washweb_org_app
      source: .
      dest: /usr/share/nginx/html/
      chdir: _site
      deploy_key:
        from_secret: drone_ssh_washnote_org
    when:
      branch:
       - main
  - name: deploy to dev.washweb.org
    image: git.coopcloud.tech/coop-cloud/docker-cp-deploy:latest
    settings:
      host: washnote.org
      port: 222
      service: dev_washweb_org_app
      source: .
      dest: /usr/share/nginx/html/
      chdir: _site
      deploy_key:
        from_secret: drone_ssh_washnote_org
    when:
      branch:
       - dev
  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - /usr/local/lib/R/site-library
    volumes:
      - name: cache
        path: /cache
      - name: lib
        path: /usr/local/lib/R/site-library


volumes:
- name: cache
  host:
    path: /tmp/drone/cache
- name: lib
  temp: {}
