project:
  type: website

website:
  title: "WASH Web"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - vision.qmd
      - contact.qmd
      - posts.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

