project:
  type: website

website:
  title: "WASH Web"
  site-url: https://washnote.org
  description: WASH Web is a set of participatory initiatives to give you and everyone you know better access to water, sanitation and hygiene information. 
  navbar:
    left:
      - href: index.qmd
        text: Home
      - vision.qmd
      - contact.qmd
      - posts.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

