project:
  type: website

website:
  site-url: https://washnote.org
  description: WASH Web is a set of participatory initiatives to give you and everyone you know better access to water, sanitation and hygiene information. 
  navbar:
    logo: "images/WASHWEB-logotype-white-1-RGB.png"
    css: logo.css
    left:
      - href: index.qmd
        text: Home
      - href: join.qmd
        text: Join
      - vision.qmd
      - href: contact.qmd
        text: Team
      - posts.qmd
      - contributor.qmd

format:
  html:
    theme:
      - custom.scss
    toc: true

editor: visual

