project:
  type: website

website:
  title: "WASHWeb"
  site-url: https://washnote.org
  description: WASH Web is a set of participatory initiatives to give you and everyone you know better access to water, sanitation and hygiene information. 
  favicon: "images/icon.png"
  navbar:
    logo: "images/WASHWEB-logotype-white-1-RGB.png"
    logo-alt: "WASHWeb logo"
    title: false
    css: logo.css
    right:
      - vision.qmd
      - href: events/index.qmd
        text: Events
      - posts.qmd
      - href: contact.qmd
        text: Team
      - href: join.qmd
        text: Join
      - contributor.qmd
    tools: 
      - icon: linkedin
        href: https://www.linkedin.com/company/washweb/
        text: WASHWeb Linkedin
      - icon: git
        href: https://git.washnote.org/WASHWeb/washweb-ideas
        text: WASHWeb git

format:
  html:
    theme:
      - custom.scss
    toc: true
    include-in-header:
      - text: |
          <script defer data-domain="washweb.org" src="https://plausible.demo.coopcloud.tech/js/script.js"></script>

editor: visual

