---
title: "Agents of Change"
---

WASH Web is a set of participatory initiatives to give you and everyone you know better access to water, sanitation and hygiene information. This web page is where you can find more information about taking part in various ways.

The WASH Web is made up of people and organizations that work to fill the water, sanitation and hygiene (WASH) gap to make data discoverable, usable and representative. WASH Web is meant to serve as an open platform and requires diverse inputs to work. Our vision cannot be realized without community support.

[Please join us to contribute.](#join)

# Working group initiatives

The working groups facilitate collaboration and discussions on four different initiatives for an improved and healthy data environment.

## Social Justice

Access to safe drinking water is a basic human right, and access to WASH systems is a social justice issue. What information is needed to improve access for marginalized people? What specific ethical issues around data collection, privacy, data ownership, and use of data need to be addressed?

## Using Data Better

There is a wealth of information and knowledge available regarding WASH data. Organizations like the JMP, GLAAS, World Bank, and OECD have generated valuable data for the sector. How can we make this publicly available data more accessible and more usable? How can we incorporate data that is more difficult to find? How can we involve smaller organizations?

## Systems Thinking

In the WASH sector, it is increasingly recognized that systems strengthening is critical to achieve universal services. Understanding and acting on systems requires that qualitative and quantitative information is used holistically in collective action. How do we bring together diverse sources of information to support systems strengthening? What are the benefits and risks of using artificial intelligence and information technology for this task?

## Accountability: 4Ws

The actors accountable for water and sanitation decision-making are often dispersed throughout diverse organizations. As a result, there is a scattered and disconnected WASH data ecosystem. It is proposed to make a WASH Registry to offer an overview of **who** is **where, when,** and doing **what** for formal change agents. Can this make the WASH sector more accountable?

## Who can take part? {#join}

Citizens, suppliers, NGOs and governments can take part to better use evidence to and to make information accessible.

## How can you participate? 

Are you interested in one of these initiatives? We facilitate the four working groups through Matrix - access them through the links below!

General WASH Web Lobby: [https://matrix.to/#/#wash-web-lobby:autonomic.zone](https://matrix.to/#/#wash-web-lobby:autonomic.zone)

Social Justice: [https://matrix.to/#/#washweb-social-justice:matrix.org](https://matrix.to/#/#washweb-social-justice:matrix.org)

Using Data Better: [https://matrix.to/#/#washweb-using-data-better:matrix.org](https://matrix.to/#/#washweb-using-data-better:matrix.org)

Systems Thinking: [https://matrix.to/#/#washweb-systems:matrix.org](https://matrix.to/#/#washweb-systems:matrix.org)

Accountability: 4Ws: [https://matrix.to/#/#accountability-4ws:matrix.org](https://matrix.to/#/#accountability-4ws:matrix.org)

New to Matrix? Go to <https://app.element.io/> to get started and make your account.

For updates on WASH Web's work, follow us on LinkedIn: <https://www.linkedin.com/company/washweb/>

Feel free to add an issue on Github: <https://github.com/WASHNote/WASHWeb/issues>
