---
title: "PRIVACY POLICY"
---

When you visit our websites and contact us or create an account on \*.washweb.org, \*.washnote.org, and \*.washnote.com we receive information about you.

We also have a commitment to reducing the use of private data to the bare minimum to provide you with these websites and associated services.

We do our best to handle your information securely and with respect and care.

## Scope

This privacy policy applies to all personal data that we process on all domains related to us. This concerns personal data of visitors and users of these websites.

We process the personal data of anyone who has visited our website and created an account, filled in data, or contacted us.

Personal data is data that can be traced back to you. If you want to know more, please visit the website of the [Dutch Data Protection Authority](https://www.autoriteitpersoonsgegevens.nl/themas/basis-avg) or the [EU GDPR website](https://gdpr.eu/).

## Purpose

We only use your personal data for the purpose for which we are allowed to use it based on our permission to use your personal data and based on data required to provide you with the service requested.

We have a commitment to keep this to the minimum required.

We don't share your personal data with others.

## WASHNote

WASHNote is responsible for the website (\*.washnote.com, \*.washnote.org, and \*.washweb.org) and therefore the responsible organisation for the use of your personal data as described in this privacy statement. Our full details are:

WASHNote\
Sumatraweg 5A\
3072ZP Rotterdam\
62484885

## What data, how long, and where?

We may use your name, address or business address, e-mail address, telephone number, and information you provide.

We keep your personal data for as long as we are required to do so by law and for as long as you use our services. We only process your personal data ourselves.

We process your data within the European Economic Area and we follow the the Dutch General Data Protection Regulation.

General rules that apply under Dutch law apply to our privacy statement.

## Data protection

We do our best to ensure your data is safe according to the latest standards. We also minimize the amount of data we hold to the bare minimum to ensure we reduce any potential risks.

## What are your data protection rights?

We would like to make sure you are fully aware of all of your data protection rights. Every user is entitled to the following:

**The right to access** -- You have the right to request WASHNote for copies of your personal data. We may charge you a small fee for this service.

**The right to rectification** -- You have the right to request that WASHNote correct any information you believe is inaccurate. You also have the right to request WASHNote to complete the information you believe is incomplete.

**The right to erasure** -- You have the right to request that WASHNote erase your personal data, under certain conditions. In some cases, may be required keep some data for 7 years for the Dutch tax authorities.

**The right to restrict processing** -- You have the right to request that WASHNote restrict the processing of your personal data, under certain conditions.

**The right to object to processing** -- You have the right to object to WASHNote's processing of your personal data, under certain conditions.

**The right to data portability** -- You have the right to request that WASHNote transfer the data that we have collected to another organization, or directly to you, under certain conditions.

If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us at our email: dickinson+privacy\@washnote.com

If you submit multiple applications or a complex request, it could potentially require additional processing time. In such instances, we will make sure to reach out to you within a maximum of 60 days. If necessary, we may also request that you verify your identity by providing specific information to confirm that you are indeed the rightful owner of the personal data in question.

## Cookies

Cookies are text files placed on your computer to collect standard Internet log information and visitor behavior information. When you visit our websites, we may collect information from you automatically through cookies or similar technology

For further information, visit allaboutcookies.org.

### How do we use cookies?

Our Company uses cookies in a range of ways to improve your experience on our website, including:

-   Keeping you signed in and storing information for your session

We do not use cookies for advertising or tracking.

### What types of cookies do we use?

There are a number of different types of cookies, however, our website uses only:

-   Functionality -- Our Company uses these cookies so that we recognize you on our website and remember your previously selected preferences. These could include what language you prefer and location you are in. A mix of first-party and third-party cookies are used.

### How to manage cookies

You can set your browser not to accept cookies, and the above website tells you how to remove cookies from your browser. However, in a few cases, some of our website features may not function as a result.

## Minors

We do not target minors with our website or as an organisation. This means that if you are under the age of 18, you need permission from a parent or guardian to use our website. If you are a minor when you visit our websites, we assume that you have received this permission before your visit.

## How to contact us

If you have a question about our privacy policy, please get in touch: dickinson+privacy\@washnote.com.
